import { type AppType } from "next/app";
import { ClerkProvider } from "@clerk/nextjs";
import { api } from "~/utils/api";

import { dark } from "@clerk/themes";

import { Toaster } from "react-hot-toast";

import "~/styles/globals.css";
import Head from "next/head";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <title>War Manager</title>
        <meta
          name="description"
          content="War Manager is your digital multi-tool to anticipate challenges in the field."
        />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link rel="mask-icon" href="/icon.png" color="#27272a" />
        <meta name="theme-color" content="#27272a" />
        <link rel="apple-touch-icon" href="logo.png" />
        <link rel="apple-touch-icon" sizes="152x152" href="logo.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="logo.png" />
        <link rel="apple-touch-icon" sizes="167x167" href="logo.png" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:url" content="https://warmanager.net" />
        <meta name="twitter:title" content="War Manager" />
        <meta
          name="twitter:description"
          content="War Manager is your digital multi-tool to anticipate challenges in the field."
        />
        <meta name="twitter:image" content="/ball_logo.png" />
        {/* <meta name="twitter:creator" content="@TaylorHowell" /> */}
        <meta property="og:type" content="website" />
        <meta property="og:title" content="MWar Manager" />
        <meta
          property="og:description"
          content="War Manager is your digital multi-tool to anticipate challenges in the field."
        />
        <meta property="og:site_name" content="War Manager" />
        <meta property="og:url" content="https://warmanager.net" />
        <meta property="og:image" content="/logo.png" />

        {/* <title>War Manager</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <ClerkProvider
        appearance={{
          baseTheme: dark,
        }}
        {...pageProps}
      >
        <Toaster position="bottom-center" />
        <Component {...pageProps} />
      </ClerkProvider>
    </>
  );
};

export { reportWebVitals } from "next-axiom";

export default api.withTRPC(MyApp);
