import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import { SignIn, SignInButton, useUser, SignOutButton } from "@clerk/nextjs";
import { use } from "react";

const Home: NextPage = () => {
  const user = useUser();

  const { data } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-900">
        <div className="just-center flex flex-col items-center rounded bg-gray-800 p-2 text-white">
          <h1 className="m-2 text-lg font-bold text-white">Sign In</h1>
          <div>
            {!user.isSignedIn && (
              <div className="rounded bg-blue-600 p-2">
                <SignInButton />
              </div>
            )}
            {!!user.isSignedIn && (
              <div className="flex flex-col text-white ">
                Hello {user.user.fullName} !!
                <div className="rounded bg-purple-600 p-2 text-center">
                  <SignOutButton />
                </div>
              </div>
            )}
          </div>
          <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
        </div>
        <div className="my-5" />
        <div className="rounded bg-gray-700 p-2 text-white">
          {data?.map((post) => (
            <div key={post.id}> {post.id.substring(0, 5)} - {post.content}</div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
